trigger:
  - master

stages:
  - stage: stage1
    jobs:  
      - job: job1
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: 'mysolution.sln'
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
  - stage: stage2
    dependsOn: stage1
    jobs:  
      - job: importantJob
        pool:
          vmImage: 'windows-latest'
        steps:
          - pwsh: 'write-host "I do nothing"'