# Multi-Stage pipeline
trigger:
- main
pool:
  vmImage: ubuntu-latest
variables:
  azureSubscription: 'azure-packt-rg'
  azureContainerRegistry:  '{"loginServer":"packtadocicd.azurecr.io", "id" : "/subscriptions/f087e49e-91bd-45f5-b53d-2b190dcfe21d/resourceGroups/packt/providers/Microsoft.ContainerRegistry/registries/packtadocicd"}'
stages:
- stage: Build
  jobs:
  - job: BuildAndPushContainers
    displayName: Build and Push Application Containers
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: 'docker-compose.yml'
        projectName: 'packt-store'
        action: 'Build services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: 'docker-compose.yml'
        projectName: 'packt-store'
        action: 'Push services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true

- stage: DeployTest
  displayName: Test
  dependsOn: Build
  jobs:
  - template: deploy.yml
    parameters:
      envName: test
      azureSubscription: ${{ azureSubscription }}

- stage: DeployProduction
  displayName: Production
  dependsOn: DeployTest
  jobs:
  - template: deploy.yml
    parameters:
      envName: produdction
      azureSubscription: ${{ azureSubscription }}
