trigger: none
pool:
  vmImage: "macos-latest"
variables:
  - group: secrets
  - name: iosReleaseDir
    value: $(Build.SourcesDirectory)/flutter/hello_world/build/ios/ipa
  - name: ipaFile
    value: $(iosReleaseDir)/hello_world.ipa
  - name: rootPath
    value: $(System.DefaultWorkingDirectory)/flutter/hello_world
jobs:
  - job: ios_to_apple_store
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: InstallAppleCertificate@2
      displayName: "Install Apple cert dist p12"
      inputs:
        certSecureFile: "Certificates_Distribution.p12"
        certPwd: "$(APPLE_CERTIFICATE_SIGNING_PASSWORD)"
        keychain: "temp"
    - task: InstallAppleProvisioningProfile@1
      displayName: "Install Apple Mobile Provisioning Profile"
      inputs:
        provisioningProfileLocation: "secureFiles"
        provProfileSecureFile: "Hello_Flutter_AppStore.mobileprovision"
    - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
      displayName: 'Flutter Install'
      inputs:
        version: custom
        customVersion: 3.10.6
    - task: Bash@3
      displayName: "Build IPA"
      inputs:
        targetType: "inline"
        script: |
          flutter build ipa --export-options-plist=$(rootPath)/ios/Runner/ExportOptions.plist
        workingDirectory: $(rootPath)
    - task: AppStoreRelease@1
      displayName: "Upload to App Store Connect"
      inputs:
        authType: 'ApiKey'
        apiKeyId: '$(IOS_APP_API_KEY)'
        apiKeyIssuerId: '$(IOS_APP_API_ISSUER)'
        apiToken: '$(IOS_AUTH_KEY_P8)'
        releaseTrack: 'TestFlight'
        appIdentifier: 'com.company.flutter'
        appType: 'iOS'
        ipaPath: $(ipaFile)
        shouldSkipWaitingForProcessing: true
        shouldSkipSubmission: true
        appSpecificId: '$(IOS_APP_ID)'