parameters:
- name: envName
  type: string
  default: 'test'
- name: azureSubscription
  type: string
  default: 'azure-packt-rg'
- name: resourceGroupName
  type: string
  default: 'packt'
- name: location
  type: string
  default: 'East US'

jobs:
- deployment: deployment_${{ parameters.envName }} 
  displayName: Deploy to ${{ parameters.envName }}
  environment: ${{ parameters.envName }}
  strategy: 
    runOnce:
      deploy:
        steps:
        - download: current
          displayName: 'Download catalog iac'
          artifact: catalog-iac
        - task: AzureResourceGroupDeployment@2
          name: catalogInfra
          displayName: 'Deploy catalog Infra'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }} 
            action: 'Create Or Update Resource Group' 
            resourceGroupName: ${{ parameters.resourceGroupName }}
            location: ${{ parameters.location }}
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/catalog-iac/template.json'
            overrideParameters: '-environmentName ${{ parameters.envName }}'
            deploymentMode: 'Incremental'
            deploymentName: 'catalog-$(Build.BuildNumber)'
            deploymentOutputs: 'catalogInfraOutputs'
        - task: PowerShell@2
          displayName: 'Get AKS clusterName'
          inputs:
            targetType: 'inline'
            script: |
              $var=ConvertFrom-Json '$(catalogInfraOutputs)'
              $value=$var.clusterName.value
              Write-Host "AKS Cluster Name: $value"
              Write-Host "##vso[task.setvariable variable=clusterName;]$value"
        - download: current
          displayName: 'Download catalog helm chart'
          artifact: catalog-helm-chart
        - task: HelmInstaller@1
          displayName: 'Install Helm'
          inputs:
            helmVersionToInstall: 3.11.3
        - task: HelmDeploy@0
          displayName: Deploy Catalog App to AKS
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscription: ${{ parameters.azureSubscription }} 
            azureResourceGroup: ${{ parameters.resourceGroupName }}
            kubernetesCluster: $(clusterName)
            releaseName: catalog
            chartType: FilePath
            chartPath: "$(Pipeline.Workspace)/catalog-helm-chart/packt-store-catalog-1.0.0.tgz"
            overrideValues: 'image.tag=$(Build.BuildNumber)'
            command: upgrade
            install: true
            waitForExecution: true
        - download: current
          displayName: 'Download cart iac'
          artifact: cart-iac
        - task: AzureResourceGroupDeployment@2
          name: cartInfra
          displayName: 'Deploy cart Infra'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }} 
            action: 'Create Or Update Resource Group' 
            resourceGroupName: ${{ parameters.resourceGroupName }}
            location: ${{ parameters.location }}
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/cart-iac/template.json'
            overrideParameters: '-environmentName ${{ parameters.envName }} -containerTag "$(Build.BuildNumber)"'
            deploymentMode: 'Incremental'
            deploymentName: 'cart-$(Build.BuildNumber)'
            deploymentOutputs: 'cartInfraOutputs'
        - download: current
          displayName: 'Download checkout iac'
          artifact: checkout-iac
        - task: AzureResourceGroupDeployment@2
          name: checkoutInfra
          displayName: 'Deploy checkout Infra'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }} 
            action: 'Create Or Update Resource Group' 
            resourceGroupName: ${{ parameters.resourceGroupName }}
            location: ${{ parameters.location }}
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/checkout-iac/template.json'
            overrideParameters: '-environmentName ${{ parameters.envName }} -containerTag "$(Build.BuildNumber)"'
            deploymentMode: 'Incremental'
            deploymentName: 'checkout-$(Build.BuildNumber)'
            deploymentOutputs: 'checkoutInfraOutputs'
        - download: current
          displayName: 'Download frontend iac'
          artifact: frontend-iac
        - task: AzureCLI@2
          displayName: 'Get Catalog App IP from AKS'
          inputs:
            azureSubscription: 'azure-packt-rg'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az aks get-credentials -g ${{ parameters.resourceGroupName }} -n $(clusterName) --overwrite-existing
              ip=`kubectl get service catalog-packt-store-catalog -o json | jq ".status.loadBalancer.ingress[0].ip"`
              echo "Catalog App IP: $ip"
              echo "##vso[task.setvariable variable=catalogAppIp;]$ip"
        - task: PowerShell@2
          displayName: 'Set App URLs'
          inputs:
            targetType: 'inline'
            script: |
              # Set the catalog app url
              $value="http://" + $(catalogAppIp) + ":5050/"
              Write-Host "Catalog App Url: $value"
              Write-Host "##vso[task.setvariable variable=catalogAppUrl;]$value"

              # Set the cart app url
              $var=ConvertFrom-Json '$(cartInfraOutputs)'
              $value=$var.containerAppFqdn.value
              $value="https://" + $var.containerAppFqdn.value + "/"
              Write-Host "Cart App Url: $value"
              Write-Host "##vso[task.setvariable variable=cartAppUrl;]$value"

              # Set the checkout app url
              $var=ConvertFrom-Json '$(checkoutInfraOutputs)'
              $value="http://" + $var.containerFQDN.value + ":5015/"
              Write-Host "Checkout App Url: $value"
              Write-Host "##vso[task.setvariable variable=checkoutAppUrl;]$value"
        - task: AzureResourceGroupDeployment@2
          name: frontendInfra
          displayName: 'Deploy frontend Infra'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }} 
            action: 'Create Or Update Resource Group' 
            resourceGroupName: ${{ parameters.resourceGroupName }}
            location: ${{ parameters.location }}
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/frontend-iac/template.json'
            overrideParameters: '-environmentName ${{ parameters.envName }} -containerTag "$(Build.BuildNumber)" -catalogAppUrl $(catalogAppUrl) -cartAppUrl $(cartAppUrl) -checkoutAppUrl $(checkoutAppUrl)'
            deploymentMode: 'Incremental'
            deploymentName: 'frontend-$(Build.BuildNumber)'
            deploymentOutputs: 'frontendInfraOutputs'
        - task: PowerShell@2
          displayName: 'Get Frontend URL'
          inputs:
            targetType: 'inline'
            script: |
              # Get the frontend app url
              $var=ConvertFrom-Json '$(frontendInfraOutputs)'
              $value=$var.frontendUrl.value
              Write-Host "Frontend Url: $value"
              Write-Host "##vso[task.setvariable variable=frontendAppUrl;]$value"
