parameters:
- name: awsConnection
  type: string
  default: 'aws-packt'
- name: location
  type: string
  default: 'us-east-1'

jobs:
- job: BuildAndPushContainers
  displayName: Build and Push Containers
  steps:
  - task: AWSShellScript@1
    displayName: 'Build and Push Containers'
    inputs:
      awsCredentials: ${{ parameters.awsConnection }}
      regionName: ${{ parameters.location }}
      failOnStandardError: false
      scriptType: 'inline'
      inlineScript: |
        # Set variables for AWS Region and Account ID
        L="${{ parameters.location }}"
        ID=`aws sts get-caller-identity --query Account --output text`
        # Login to ECR
        aws ecr get-login-password | docker login --username AWS --password-stdin $ID.dkr.ecr.$L.amazonaws.com
        # Build images with docker-compose
        docker-compose build
        # Tag and push images to ECR
        declare -a services=("catalog" "cart" "checkout" "frontend")
        declare -a tags=("$(Build.BuildNumber)" "latest")
        for s in "${services[@]}"
        do
          echo "Pushing images for $s"
          for t in "${tags[@]}"
          do
            docker tag packt-store-$s:latest $ID.dkr.ecr.$L.amazonaws.com/packt-store-$s:$t
            docker push $ID.dkr.ecr.$L.amazonaws.com/packt-store-$s:$t
          done
        done
